#!/bin/bash
#
# chkconfig: 35 90 12
# description: A server
#
# Get function from functions library
. /etc/init.d/functions

LOG=/var/log/neo4j.log
SERVICE=neo4j
APP="/opt/las/app/neo4j-community-2.0.0-M06/bin/neo4j"

log_message () {
    echo $* >> $LOG
}

# Start the service 
start() {
        log_message "echo -n Starting $SERVICE server: "
        $APP start &
        ### Create the lock file ###
        touch /var/lock/subsys/$SERVICE
        success $"$SERVICE server startup"
        echo
}
# Restart the service
stop() {
        log_message "echo -n Stopping $SERVICE server: "
        #killproc $SERVICE
	$APP stop
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/$SERVICE
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status FOO
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
