#!/bin/sh
 
#
# chkconfig: 35 99 99
# description: LAS Instrumentation - Event Engine
#
 
. /etc/rc.d/init.d/functions
 
USER="scox"
 
SERVICE=node
DAEMON_QUAL="NODE_ENV=dev"
PROCESSMGR="/opt/las/app/node-v0.10.21-linux-x64/bin/pm2"
DAEMON="$PROCESSMGR start /opt/las/app/las-instr-fep/pm2_cluster.json"
#DAEMON="NODE_ENV=dev /opt/las/app/node-v0.10.21-linux-x64/bin/node"
ROOT_DIR="/opt/las/app/las-instr-fep"
 
SERVER="$ROOT_DIR/app.js"
LOG_FILE=/opt/las/var/app.log
 
LOCK_FILE="/var/lock/subsys/node-server"

#set -x
 
do_start () {
    if [ ! -f "$LOCK_FILE" ] ; then
        echo -n $"Starting $SERVICE: "
        runuser -l "$USER" -c "$DAEMON_QUAL $DAEMON >> $LOG_FILE &" && echo_success || echo_failure
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch $LOCK_FILE
    else
        echo "$SERVER is locked ($LOCK_FILE)"
        RETVAL=1
    fi
}
do_status () {
    runuser -l "$USER" -c "$PROCESSMGR list"
}
do_stop () {
    echo -n $"Stopping $SERVER: "
    #kill -9 $( ps -ef | grep node | grep app.js | awk '{ print $2 }' ) > /dev/null 2>&1 && echo_success || echo_failure
    runuser -l "$USER" -c "$PROCESSMGR stop all"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

case "$1" in
        start)
                do_start
                ;;
        status)
                do_status
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|status|stop|restart}"
                RETVAL=1
esac
 
exit $RETVAL
