#!/bin/sh
 
#
# chkconfig: 2345 50 90
# description: skylr-zookeeper
#
 
. /etc/rc.d/init.d/functions
 
USER="scox"

ROOT=/opt/las
SERVICE=zookeeper
LOG_FILE=/opt/las/var/zookeeper.log
LOCK_FILE="/var/lock/subsys/$SERVICE-server"

#set -x
 
do_start () {
    if [ ! -f "$LOCK_FILE" ] ; then
        echo -n $"Starting $SERVICE: "
	echo "-------------------------------> $SERVICE" >> /opt/las/zk.log
	runuser -l "$USER" -c "source $ROOT/setup.sh && skylr zk start >> $LOG_FILE &" && echo_success || echo_failure
    else
        echo "$SERVER is locked ($LOCK_FILE)"
        RETVAL=1
    fi
}
do_status () {
    if [[ "$(ps -ef | grep -v grep | grep -c QuorumPeerMain)" -gt 0 ]]; then
	echo Zookeeper is on
    else
	echo Zookeeper is off
    fi
}
do_stop () {
    echo -n $"Stopping $SERVER: "
    ps -ef | egrep "zookeeper-server-start.sh|QuorumPeerMain" | grep -v grep | awk '{ print $2 }' 
    ps -ef | egrep "zookeeper-server-start.sh|QuorumPeerMain" | grep -v grep | awk '{ print $2 }' | xargs kill -9
    RETVAL=$?
}
case "$1" in
        start)
                do_start
                ;;
        status)
                do_status
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|status|stop|restart}"
                RETVAL=1
esac
 
exit $RETVAL
