#!/bin/bash
#
# chkconfig: 2345 60 80
# description: A server
#
# Get function from functions library
. /etc/init.d/functions

user=skylr
LOG=/var/log/mongod.log
SERVICE=mongod
DATA=/var/skylr/data/mongodb
APP="/opt/app/skylr_app/mongodb-linux-x86_64-2.4.8/bin/mongod --dbpath=$DATA"

log_message () {
    echo $* >> $LOG
}

# Start the service 
start() {
        log_message "echo -n Starting $SERVICE server: "
	runuser $user -c "$APP &"
        touch /var/lock/subsys/$SERVICE
        success $"$SERVICE server startup"
        echo
}
status () {
    if [[ "$(ps -ef | grep -v grep | grep dbpath | grep -c mongod)" -gt 0 ]]; then
	echo $SERVICE is on
    else
	echo $SERVICE is off
    fi
}
# Restart the service
stop() {
        log_message "echo -n Stopping $SERVICE server: "
	ps -ef | grep $SERVICE | grep -v grep | xargs kill -SIGTERM
        rm -f /var/lock/subsys/$SERVICE
        echo
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status mongod
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
