#!/bin/sh
 
#
# chkconfig: 2345 80 60
# description: LAS Instrumentation - Event Engine
#
 
. /etc/rc.d/init.d/functions
 
USER="scox"

SKYLR_HOME=/opt/las/skylr
SKYLR_APP=/opt/las/skylr_stack

SERVICE=node
NODE_ENV=prod
PROCESSMGR="$SKYLR_APP/node-v0.10.22-linux-x64/bin/pm2"
DAEMON="$PROCESSMGR -f start $SKYLR_HOME/pm2.json"
SERVER="$SKYLR_HOME/app.js"
LOG_FILE=/opt/las/var/app.log
 
LOCK_FILE="/var/lock/subsys/node-server"

set -x
 
do_start () {
    if [ ! -f "$LOCK_FILE" ] ; then
        echo -n $"Starting $SERVICE: "
        runuser -l "$USER" -c "cd $SKYLR_HOME && NODE_ENV=$NODE_ENV $DAEMON >> $LOG_FILE &" && echo_success || echo_failure
        #RETVAL=$?
        #echo
        #[ $RETVAL -eq 0 ] && touch $LOCK_FILE
    else
        echo "$SERVER is locked ($LOCK_FILE)"
        RETVAL=1
    fi
}
do_status () {
    runuser -l "$USER" -c "$PROCESSMGR list"
}
do_stop () {
    echo -n $"Stopping $SERVER: "
    #kill -9 $( ps -ef | grep node | grep app.js | awk '{ print $2 }' ) > /dev/null 2>&1 && echo_success || echo_failure
    runuser -l "$USER" -c "$PROCESSMGR kill"
    RETVAL=$?
    echo
    #[ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
    $RETVAL
}
case "$1" in
        start)
                do_start
                ;;
        status)
                do_status
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
                do_start
                ;;
        *)
                echo "Usage: $0 {start|status|stop|restart}"
                RETVAL=1
esac
 
exit $RETVAL
